services:
  - type: web
    name: lovemore-strapi
    env: node
    plan: free
    buildCommand: npm install && npm run build
    startCommand: npm run start
    envVars:
      - key: NODE_VERSION
        value: 22
      - key: NODE_ENV
        value: production
      - key: DATABASE_CLIENT
        value: postgres
      - key: DATABASE_SSL
        value: true
      - key: DATABASE_SSL_REJECT_UNAUTHORIZED
        value: false
      - key: HOST
        value: 0.0.0.0
      - key: PORT
        value: 10000
